FROM node:20-alpine

RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @monitor/event-contract build \
 && pnpm --filter @monitor/ingest-gateway build \
 && pnpm --filter @monitor/processor-worker build \
 && pnpm --filter @monitor/query-service build

CMD ["pnpm", "--filter", "@monitor/ingest-gateway", "start"]
